services:
  app:
    build: .
    env_file:
      - path: .env
        required: false
    volumes:
      - .:/app
    working_dir: /app
    command: ["pytest", "--cov=app", "--cov-report=term-missing", "-v"]
